config/routes.rb
Rails.application.routes.draw do
  resources :games

  devise_for :users
  root "users#index"
  get "about" => "pages#about"

  resources :users

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :scores
end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :game
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  
  #has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  #validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_and_belongs_to_many :games
  has_many :scores, through: :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  def update
    if @game.update(game_params)
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
      redirect_to games_url, notice: 'Game was successfully destroyed.'
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params[:game]
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	  @user = User.find(params[:id])
	end
	def create
	  @user = User.create( user_params )
	end

	private

	# Use strong_parameters for attribute whitelisting
	# Be sure to update your create() and update() controller methods.

	def user_params
	  params.require(:user).permit(:avatar)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h3>Games</h3>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Winner</th>
        <th>Points</th>
        <th>Looser</th>
        <th>Points</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td>Kendall</td>
          <td>21</td>
          <td>Brady</td>
          <td>2</td>
          <td><%= link_to 'Show', game %></td>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "ACE", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Games", games_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if user_signed_in? %>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
    	<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	<div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Ace</h1>
<p>Really cool ping pong app</p>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Welcome to ACE</h1>
	<% if user_signed_in? %>
		#do something
	<% else %>
		<p>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	<% end %>
</div>

app/views/users/index.html.erb
<h3>Ace Ping Pong</h3>

<%= link_to 'New Game', new_game_path %>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Profile Pic</th>
        <th>Name</th>
        <th>Wins</th>
        <th>Losses</th>
        <th>Total Points</th>
        <th>Rank</th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td>#</td>
          <td>Kendall</td>
          <td>23</td>
          <td>2</td>
          <td>1234</td>
          <td>#1</td>
        </tr>
    </tbody>
  </table>
</div>